// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CrosswordGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("size")]
        public long Size { get; set; }

        [JsonProperty("difficulty")]
        public string Difficulty { get; set; }

        [JsonProperty("theme")]
        public string Theme { get; set; }

        [JsonProperty("grid")]
        public string[][] Grid { get; set; }

        [JsonProperty("across")]
        public Across[] Across { get; set; }

        [JsonProperty("down")]
        public Across[] Down { get; set; }

        [JsonProperty("wordCount")]
        public long WordCount { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }

        [JsonProperty("image")]
        public Image Image { get; set; }

        [JsonProperty("solutionImage")]
        public Image SolutionImage { get; set; }
    }

    public partial class Across
    {
        [JsonProperty("number")]
        public long Number { get; set; }

        [JsonProperty("clue")]
        public string Clue { get; set; }

        [JsonProperty("answer")]
        public string Answer { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("imageName")]
        public string ImageName { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("downloadURL")]
        public Uri DownloadUrl { get; set; }

        [JsonProperty("expires")]
        public long Expires { get; set; }
    }
}
